In [ ]:
# Cs 1
!pip install yfinance

In [ ]:
# cs 2
# Importing Prophet and yahoo finance packages
from prophet import Prophet
import yfinance as yf

In [ ]:
# Cs 3
# Set start dates and end dates
start_date = '2015-01-01'
end_date = '2025-07-19'

ticker = 'NVDA'

In [ ]:
# cs 4
# Importing the stock data
data = yf.download(ticker, start_date, end_date)

data

/tmp/ipython-input-14-4293860288.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start_date, end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2015-01-02    0.483066    0.486665    0.475386    0.483066  113680000
2015-01-05    0.474906    0.484505    0.472747    0.483066  197952000
2015-01-06    0.460508    0.476106    0.460028    0.475626  197764000
2015-01-07    0.459308    0.467947    0.457868    0.463868  321808000
2015-01-08    0.476586    0.479466    0.464348    0.464588  283780000
...                ...         ...         ...         ...        ...
2025-07-14  164.070007  165.490005  162.020004  165.369995  136975800
2025-07-15  170.699997  172.399994  169.199997  171.190002  230627400
2025-07-16  171.369995  171.750000  168.899994  171.059998  158831500
2025-07-17  173.000000  174.160004  170.830002  172.020004  160841100
2025-07-18  172.410004  174.250000  171.259995  173.639999  146107600

[2651 rows x 5 columns]

In [ ]:
# cs 5
# Resetting the index
data.reset_index(inplace=True)

data

Price        Date       Close        High         Low        Open     Volume
Ticker                   NVDA        NVDA        NVDA        NVDA       NVDA
0      2015-01-02    0.483066    0.486665    0.475386    0.483066  113680000
1      2015-01-05    0.474906    0.484505    0.472747    0.483066  197952000
2      2015-01-06    0.460508    0.476106    0.460028    0.475626  197764000
3      2015-01-07    0.459308    0.467947    0.457868    0.463868  321808000
4      2015-01-08    0.476586    0.479466    0.464348    0.464588  283780000
...           ...         ...         ...         ...         ...        ...
2646   2025-07-14  164.070007  165.490005  162.020004  165.369995  136975800
2647   2025-07-15  170.699997  172.399994  169.199997  171.190002  230627400
2648   2025-07-16  171.369995  171.750000  168.899994  171.059998  158831500
2649   2025-07-17  173.000000  174.160004  170.830002  172.020004  160841100
2650   2025-07-18  172.410004  174.250000  171.259995  173.639999  146107600

[2651 rows x 6 columns]

In [ ]:
# Cs 6
# Selecting date and adjusted close
data = data[['Date', 'Close']]

data

Price        Date       Close
Ticker                   NVDA
0      2015-01-02    0.483066
1      2015-01-05    0.474906
2      2015-01-06    0.460508
3      2015-01-07    0.459308
4      2015-01-08    0.476586
...           ...         ...
2646   2025-07-14  164.070007
2647   2025-07-15  170.699997
2648   2025-07-16  171.369995
2649   2025-07-17  173.000000
2650   2025-07-18  172.410004

[2651 rows x 2 columns]

In [ ]:
# Cs 7
# Renaming date as ds and adj close as y
data.columns = ['ds', 'y']

data

             ds           y
0    2015-01-02    0.483066
1    2015-01-05    0.474906
2    2015-01-06    0.460508
3    2015-01-07    0.459308
4    2015-01-08    0.476586
...         ...         ...
2646 2025-07-14  164.070007
2647 2025-07-15  170.699997
2648 2025-07-16  171.369995
2649 2025-07-17  173.000000
2650 2025-07-18  172.410004

[2651 rows x 2 columns]

In [ ]:
# Code snippet 8
# Initialize Prophet
model = Prophet()

# Code snippet
# Training the model with the date and y values
model.fit(data)

# Code snippet
# Setting a future dataframe
future = model.make_future_dataframe(periods=30)

# Code snippet
# Predicting the incidents for future period
forecast = model.predict(future)

# Code snippet
# Creating a subset with predictions, lower and upper values
forecast_subset = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

In [ ]:
# Code snippet 8.1
# Creating a final dataset with actuals, predictions, lower and upper values
import pandas as pd
# Ensure 'ds' columns in both dataframes are datetime type before merging
data['ds'] = pd.to_datetime(data['ds'])
forecast_subset['ds'] = pd.to_datetime(forecast_subset['ds'])

# Merge on 'ds' column
forecast_subset_merged = pd.merge(data, forecast_subset[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], on='ds', how='outer')
forecast_subset_merged

/tmp/ipython-input-25-1362546686.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_subset['ds'] = pd.to_datetime(forecast_subset['ds'])

             ds         y        yhat  yhat_lower  yhat_upper
0    2015-01-02  0.483066   -0.228558   -9.595826    8.619868
1    2015-01-05  0.474906   -0.205221   -9.932385    8.879133
2    2015-01-06  0.460508   -0.206110   -9.200860    9.159925
3    2015-01-07  0.459308   -0.227568   -9.700660    9.424851
4    2015-01-08  0.476586   -0.140694   -9.883142    9.510098
...         ...       ...         ...         ...         ...
2676 2025-08-13       NaN  162.178268  152.561871  171.892923
2677 2025-08-14       NaN  162.574959  152.693461  172.374704
2678 2025-08-15       NaN  162.881760  153.159956  172.032161
2679 2025-08-16       NaN  163.301161  153.431447  172.334088
2680 2025-08-17       NaN  163.598711  154.129912  173.063095

[2681 rows x 5 columns]

In [ ]:
# Code snippet 9
# Exporting the predictions
forecast_subset_merged.to_csv('NVDA Stock Price predictions.csv')