In [ ]:
# Code snippet 1
# importing pandas and other relevant packages
import pandas as pd
import numpy as np

# Importing SQLlite 3 package (to run SQL queries)
import sqlite3

In [ ]:
# Code snippet 2
# Importing the dataset
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Tarrant%20County%20Income%20Dataset%20SQL%20CSV.csv')

data

,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 3
# Creating a sample (dummy) database as a connection
conn = sqlite3.connect('sample.db')

In [ ]:
# Code snippet 4
# Storing the pandas dataframe db as a table in the sample database
data.to_sql('df_sql', conn)

32561

In [ ]:
# Code snippet 5
# Selecting all the data from the table
sql_query = "SELECT * FROM df_sql"
df1 = pd.read_sql(sql_query, conn)
df1

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 6
# Selecting all the data from the table where age > 50
sql_query = "SELECT * FROM df_sql WHERE age > 50"
df1 = pd.read_sql(sql_query, conn)
df1

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,3,53,Private,234721,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
1,7,52,Self-emp-not-inc,209642,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
2,21,54,Private,302146,HS-grad,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
3,24,59,Private,109015,HS-grad,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
4,25,56,Local-gov,216851,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6455,32542,72,None,129912,HS-grad,Married-civ-spouse,None,Husband,White,Male,0,0,25,United-States,<=50K
6456,32548,65,Self-emp-not-inc,99359,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
6457,32554,53,Private,321865,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
6458,32558,58,Private,151910,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
6459,32560,52,Self-emp-inc,287927,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Code snippet 7
# Selecting all the data from the table where age <= 50
sql_query = "SELECT * FROM df_sql WHERE age <= 50"
df1 = pd.read_sql(sql_query, conn)
df1

,index,Age,Workclass,Profile,Education,Marital_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_Week,Native_Country,Income
0,0,39,State-gov,77516,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,1,50,Self-emp-not-inc,83311,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,2,38,Private,215646,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,4,28,Private,338409,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,5,37,Private,284582,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26096,32553,32,Private,116138,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
26097,32555,22,Private,310152,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
26098,32556,27,Private,257302,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
26099,32557,40,Private,154374,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
26100,32559,22,Private,201490,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
# Code snippet 8
# Selecting all the data from the table where age <= 30 and income > 50k
sql_query = ''' SELECT * FROM df_sql WHERE age <= 30 and income = ">50k" '''
df1 = pd.read_sql(sql_query, conn)
df1

Empty DataFrame
Columns: [index, Age, Workclass, Profile, Education, Marital_Status, Occupation, Relationship, Race, Gender, Capital_Gain, Capital_Loss, Hours_per_Week, Native_Country, Income]
Index: []

In [ ]:
# Code snippet 9
# Selecting all the distinct marital statuses
sql_query = ''' SELECT distinct(Marital_Status) FROM df_sql  '''
df1 = pd.read_sql(sql_query, conn)
df1

          Marital_Status
0          Never-married
1     Married-civ-spouse
2               Divorced
3  Married-spouse-absent
4              Separated
5      Married-AF-spouse
6                Widowed

In [ ]:
# Code snippet 10
# Selecting the marital status and the respective counts, order by count descending
sql_query = ''' SELECT Marital_Status, count(*) FROM df_sql group by Marital_Status order by count(*) desc'''
df1 = pd.read_sql(sql_query, conn)
df1

          Marital_Status  count(*)
0     Married-civ-spouse     14976
1          Never-married     10683
2               Divorced      4443
3              Separated      1025
4                Widowed       993
5  Married-spouse-absent       418
6      Married-AF-spouse        23

In [ ]:
# Code snippet 11
# Selecting the education and the respective counts, order by count descending
sql_query = ''' SELECT education, count(*) FROM df_sql group by education order by count(*) desc'''
df1 = pd.read_sql(sql_query, conn)
df1

       Education  count(*)
0        HS-grad     10501
1   Some-college      7291
2      Bachelors      5355
3        Masters      1723
4      Assoc-voc      1382
5           11th      1175
6     Assoc-acdm      1067
7           10th       933
8        7th-8th       646
9    Prof-school       576
10           9th       514
11          12th       433
12     Doctorate       413
13       5th-6th       333
14       1st-4th       168
15     Preschool        51

In [ ]:
# Code snippet 12
# Selecting the education and the respective counts (with atleast 1000 records), order by count descending
sql_query = ''' SELECT education, count(*) FROM df_sql group by education having count(*) > 1000 order by count(*) desc'''
df1 = pd.read_sql(sql_query, conn)
df1

      Education  count(*)
0       HS-grad     10501
1  Some-college      7291
2     Bachelors      5355
3       Masters      1723
4     Assoc-voc      1382
5          11th      1175
6    Assoc-acdm      1067

from matplotlib import pyplot as plt
_df_0['count(*)'].plot(kind='hist', bins=20, title='count(*)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Education').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['count(*)'].plot(kind='line', figsize=(8, 4), title='count(*)')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_3['Education'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_3, x='count(*)', y='Education', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# Code snippet 13
# Selecting the Occupation and the respective counts, order by count descending
sql_query = ''' SELECT occupation, count(*) FROM df_sql group by occupation order by count(*) desc'''
df1 = pd.read_sql(sql_query, conn)
df1

           Occupation  count(*)
0      Prof-specialty      4140
1        Craft-repair      4099
2     Exec-managerial      4066
3        Adm-clerical      3770
4               Sales      3650
5       Other-service      3295
6   Machine-op-inspct      2002
7                None      1843
8    Transport-moving      1597
9   Handlers-cleaners      1370
10    Farming-fishing       994
11       Tech-support       928
12    Protective-serv       649
13    Priv-house-serv       149
14       Armed-Forces         9