In [ ]:
# Code snippet 1
# Importing the time series data
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Statefarm%20Incidents.csv')

data

        Date  Incidents
0     3/1/23        364
1     3/2/23        309
2     3/3/23        362
3     3/4/23        320
4     3/5/23        405
..       ...        ...
360  2/24/24        359
361  2/25/24        313
362  2/26/24        410
363  2/27/24        393
364  2/28/24        331

[365 rows x 2 columns]

In [ ]:
# Code snippet 2
# Importing Prophet package for time series regression ML modeling
from prophet import Prophet

In [ ]:
# Code snippet 3
# Renaming Date as ds and Incidents as y
data.columns = ['ds', 'y']

data

          ds    y
0     3/1/23  364
1     3/2/23  309
2     3/3/23  362
3     3/4/23  320
4     3/5/23  405
..       ...  ...
360  2/24/24  359
361  2/25/24  313
362  2/26/24  410
363  2/27/24  393
364  2/28/24  331

[365 rows x 2 columns]

In [ ]:
# Code snippet 4
# Initialize Prophet
model = Prophet()

In [ ]:
# Code snippet 5
# Training the model with the date and y values
model.fit(data)

In [ ]:
# Code snippet 6
# Setting a future dataframe
future = model.make_future_dataframe(periods=30)

In [ ]:
# Code snippet 7
# Predicting the incidents for future period
forecast = model.predict(future)

In [ ]:
# Code snippet 8
# Displaying the predictions
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-01,267.113716,203.220019,322.531721,267.113716,267.113716,-8.087218,-8.087218,-8.087218,-8.087218,-8.087218,-8.087218,0.0,0.0,0.0,259.026498
1,2023-03-02,267.966863,181.414119,293.626461,267.966863,267.966863,-30.323146,-30.323146,-30.323146,-30.323146,-30.323146,-30.323146,0.0,0.0,0.0,237.643716
2,2023-03-03,268.820010,233.573457,346.988186,268.820010,268.820010,22.061331,22.061331,22.061331,22.061331,22.061331,22.061331,0.0,0.0,0.0,290.881340
3,2023-03-04,269.673157,222.815226,339.294762,269.673157,269.673157,10.809082,10.809082,10.809082,10.809082,10.809082,10.809082,0.0,0.0,0.0,280.482238
4,2023-03-05,270.526303,225.237968,342.469521,270.526303,270.526303,12.558849,12.558849,12.558849,12.558849,12.558849,12.558849,0.0,0.0,0.0,283.085152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,2024-03-25,322.645769,258.720041,375.960902,321.376763,323.996473,-5.205703,-5.205703,-5.205703,-5.205703,-5.205703,-5.205703,0.0,0.0,0.0,317.440065
391,2024-03-26,322.302242,259.064242,378.466675,320.959885,323.749673,-1.813194,-1.813194,-1.813194,-1.813194,-1.813194,-1.813194,0.0,0.0,0.0,320.489048
392,2024-03-27,321.958715,258.606115,370.701352,320.518380,323.501190,-8.087218,-8.087218,-8.087218,-8.087218,-8.087218,-8.087218,0.0,0.0,0.0,313.871497
393,2024-03-28,321.615188,234.231204,351.071002,320.019419,323.245824,-30.323146,-30.323146,-30.323146,-30.323146,-30.323146,-30.323146,0.0,0.0,0.0,291.292041
394,2024-03-29,321.271661,286.317289,402.815135,319.567914,322.978132,22.061331,22.061331,22.061331,22.061331,22.061331,22.061331,0.0,0.0,0.0,343.332991

In [ ]:
# Code snippet 9
# Creating a subset with predictions, lower and upper values
forecast_subset = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]


forecast_subset

            ds        yhat  yhat_lower  yhat_upper
0   2023-03-01  259.026498  203.220019  322.531721
1   2023-03-02  237.643716  181.414119  293.626461
2   2023-03-03  290.881340  233.573457  346.988186
3   2023-03-04  280.482238  222.815226  339.294762
4   2023-03-05  283.085152  225.237968  342.469521
..         ...         ...         ...         ...
390 2024-03-25  317.440065  258.720041  375.960902
391 2024-03-26  320.489048  259.064242  378.466675
392 2024-03-27  313.871497  258.606115  370.701352
393 2024-03-28  291.292041  234.231204  351.071002
394 2024-03-29  343.332991  286.317289  402.815135

[395 rows x 4 columns]

In [ ]:
# Code snippet 9.1
# Creating a final dataset with actuals, predictions, lower and upper values

# Ensure 'ds' columns in both dataframes are datetime type before merging
data['ds'] = pd.to_datetime(data['ds'])
forecast_subset['ds'] = pd.to_datetime(forecast_subset['ds'])

# Merge on 'ds' column
forecast_subset_merged = pd.merge(data, forecast_subset[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], on='ds', how='outer')
forecast_subset_merged

/tmp/ipython-input-19-2913021488.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_subset['ds'] = pd.to_datetime(forecast_subset['ds'])

            ds      y        yhat  yhat_lower  yhat_upper
0   2023-03-01  364.0  259.026498  203.220019  322.531721
1   2023-03-02  309.0  237.643716  181.414119  293.626461
2   2023-03-03  362.0  290.881340  233.573457  346.988186
3   2023-03-04  320.0  280.482238  222.815226  339.294762
4   2023-03-05  405.0  283.085152  225.237968  342.469521
..         ...    ...         ...         ...         ...
390 2024-03-25    NaN  317.440065  258.720041  375.960902
391 2024-03-26    NaN  320.489048  259.064242  378.466675
392 2024-03-27    NaN  313.871497  258.606115  370.701352
393 2024-03-28    NaN  291.292041  234.231204  351.071002
394 2024-03-29    NaN  343.332991  286.317289  402.815135

[395 rows x 5 columns]

In [ ]:
# Code snippet 10
# Exporting the predictions
forecast_subset_merged.to_csv('Statefarm incidents forecast subset.csv')